#!/usr/bin/env python3
"""Assemble the Windows bundle: bundles/checklist-windows.zip.

    python3 scripts/build-windows.py                 with the Python runtime
    python3 scripts/build-windows.py --no-python     assets and helper only

`make windows` is the way in; this is what it runs, after `make build`.

architecture.md 7.1 settles what is in the zip and why it is a zip rather than
an installer: an official embeddable Python plus a shortcut to Microsoft's own
signed pythonw.exe. No .exe is produced, deliberately -- SmartScreen never
fires, and there is no installer, no pip and no admin rights anywhere in it.

Two rules the assembled zip is held to. No console window on the path a user
actually takes -- Setup.vbs runs under wscript.exe and the shortcut it writes
targets pythonw.exe, neither of which has one. And no path in the bundle that
points outside the folder it was unzipped into, which check_self_contained()
enforces here rather than leaving to be discovered on the Windows side: this
build usually runs under WSL, and a bundle reaching back over \\wsl.localhost
would work only on the machine that built it.

The runtime is downloaded once into .build-cache/ and staged into the zip. That
download is the one thing here that touches the network, and --no-python skips
it for a machine that already has Python on PATH.

Python 3 stdlib only, so this runs anywhere the project does.
"""

from __future__ import annotations

import argparse
import struct
import sys
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"
PACKAGING = ROOT / "packaging" / "windows"
CACHE = ROOT / ".build-cache"
OUT = ROOT / "bundles" / "checklist-windows.zip"

PYTHON_VERSION = "3.12.10"
APP_NAME = "Checklist"
PORT = 38531

# The whole installation, and the only thing in the zip anyone is asked to
# double-click. It runs under wscript.exe: no console window at any point, and
# no ExecutionPolicy to satisfy first -- which is why this is a .vbs and not the
# .ps1 it replaced. architecture.md 7.1.
#
# Every path it names is resolved from the folder holding the script, so the
# bundle carries nothing from the machine that built it and works wherever it
# was unzipped.
VBS = r'''Option Explicit
' Generated by scripts/build-windows.py -- do not edit by hand.
'
' Unzip the bundle, double-click this once. It asks which folder your cloud
' client keeps in sync, remembers the answer in folder.txt, puts %(name)s on
' your desktop, and starts the app. After that the desktop icon is the way in
' and nothing here runs again.

Const APP_NAME = "%(name)s"
Const PORT     = %(port)s

Dim shell, fso, here, server, icon, pythonw, folderFile, folder, desktop

Set shell = CreateObject("WScript.Shell")
Set fso   = CreateObject("Scripting.FileSystemObject")

here   = fso.GetParentFolderName(WScript.ScriptFullName)
server = fso.BuildPath(here, "serve.py")
icon   = fso.BuildPath(here, APP_NAME & ".ico")

If Not fso.FileExists(server) Then
    MsgBox "serve.py is not here:" & vbCrLf & vbCrLf & here & vbCrLf & vbCrLf & _
           "Unzip the whole bundle and run this from inside it.", vbCritical, APP_NAME
    WScript.Quit 1
End If

pythonw = FindPythonw()
If pythonw = "" Then
    MsgBox "No pythonw.exe to run the helper with." & vbCrLf & vbCrLf & _
           "This bundle was built without the Python runtime and there is none " & _
           "on PATH. Install Python 3, or rebuild the bundle with the runtime in it.", _
           vbCritical, APP_NAME
    WScript.Quit 1
End If

' --- the folder: asked once, remembered beside this script -----------------

folderFile = fso.BuildPath(here, "folder.txt")
folder = ReadFolder(folderFile)
If folder = "" Then
    folder = AskFolder()
    ' Cancelled. Nothing written and nothing started, so running this again is
    ' the whole of the retry.
    If folder = "" Then WScript.Quit 0
    WriteFolder folderFile, folder
End If

' --- the shortcut, on the desktop and here ---------------------------------
'
' Firefox does not install PWAs, so this is what puts the app on the taskbar.
' It targets pythonw.exe -- Microsoft's own signed binary, and the one without
' a console -- which is also why no .exe is shipped: SmartScreen never fires.

desktop = shell.SpecialFolders("Desktop")
If desktop <> "" Then MakeShortcut desktop
MakeShortcut here

' --- start it ---------------------------------------------------------------
'
' 0 is a hidden window; the helper opens the browser itself. Under pythonw.exe
' a failure has nowhere to print, so wait for the port to answer and name the
' launcher that does have a console if it never does.

shell.Run Quoted(pythonw) & " " & Quoted(server) & " --folder " & Quoted(folder), 0, False

If Not Answers() Then
    MsgBox APP_NAME & " did not start." & vbCrLf & vbCrLf & _
           "Run " & APP_NAME & ".bat instead: it is the same helper with a " & _
           "console window, and it will say why.", vbExclamation, APP_NAME
End If

' ---------------------------------------------------------------------------

Function Quoted(value)
    Quoted = """" & value & """"
End Function

' The runtime staged in the bundle, else one on PATH. PATH is walked here
' rather than shelled out to, because `where` would flash a console window.
Function FindPythonw()
    Dim bundled, dirs, i, candidate
    FindPythonw = ""
    bundled = fso.BuildPath(here, "python\pythonw.exe")
    If fso.FileExists(bundled) Then
        FindPythonw = bundled
        Exit Function
    End If
    dirs = Split(shell.ExpandEnvironmentStrings("%%PATH%%"), ";")
    For i = 0 To UBound(dirs)
        candidate = Trim(Replace(dirs(i), """", ""))
        If candidate <> "" Then
            candidate = fso.BuildPath(candidate, "pythonw.exe")
            If fso.FileExists(candidate) Then
                FindPythonw = candidate
                Exit Function
            End If
        End If
    Next
End Function

' &H41 is BIF_RETURNONLYFSDIRS + BIF_NEWDIALOGSTYLE: a real directory, and the
' dialog that can make one -- the folder often does not exist until now.
Function AskFolder()
    Dim picked
    AskFolder = ""
    On Error Resume Next
    Set picked = CreateObject("Shell.Application").BrowseForFolder( _
        0, "Which folder does your cloud client keep in sync?", &H41)
    On Error GoTo 0
    If Not (picked Is Nothing) Then AskFolder = picked.Self.Path
End Function

' Written and read as plain text in the system codepage, because the .bat reads
' the same file with `set /p` and that is the encoding it understands.
Function ReadFolder(path)
    Dim stream, line
    ReadFolder = ""
    If Not fso.FileExists(path) Then Exit Function
    line = ""
    Set stream = fso.OpenTextFile(path, 1)
    If Not stream.AtEndOfStream Then line = Trim(stream.ReadLine)
    stream.Close
    ReadFolder = line
End Function

Sub WriteFolder(path, value)
    Dim stream
    Set stream = fso.CreateTextFile(path, True)
    stream.WriteLine value
    stream.Close
End Sub

Sub MakeShortcut(dir)
    Dim link
    On Error Resume Next
    Set link = shell.CreateShortcut(fso.BuildPath(dir, APP_NAME & ".lnk"))
    link.TargetPath       = pythonw
    link.Arguments        = Quoted(server) & " --folder " & Quoted(folder)
    link.WorkingDirectory = here
    link.Description      = APP_NAME & " - opens in your browser"
    If fso.FileExists(icon) Then link.IconLocation = icon
    link.Save
    On Error GoTo 0
End Sub

' Ten seconds of asking the helper whether it is up. It binds 127.0.0.1, so
' this reaches nothing but the process just started.
Function Answers()
    Dim http, i
    Answers = False
    For i = 1 To 20
        WScript.Sleep 500
        On Error Resume Next
        Set http = CreateObject("MSXML2.XMLHTTP")
        http.Open "GET", "http://127.0.0.1:" & PORT & "/", False
        http.Send
        If Err.Number = 0 And http.Status = 200 Then
            On Error GoTo 0
            Answers = True
            Exit Function
        End If
        Err.Clear
        On Error GoTo 0
    Next
End Function
'''

# The diagnostic, and the only thing in the bundle with a window. Setup.vbs is
# the normal way in; this one exists so a launch that fails silently under
# pythonw.exe can be made to say why.
BAT = r"""@echo off
rem Generated by scripts/build-windows.py -- do not edit by hand.
rem Setup.vbs is the normal way in. This is the same helper under python.exe,
rem with a console, for when the normal way in starts nothing.
cd /d "%~dp0"

if exist "folder.txt" goto :have_folder
echo.
echo Which folder does your cloud client keep in sync?
echo   for example  C:\Users\%USERNAME%\Dropbox\checklist
echo.
set /p "FOLDER=Folder: "
>folder.txt echo(%FOLDER%

:have_folder
set /p FOLDER=<folder.txt
if not defined FOLDER (
  echo no folder given. Delete folder.txt and try again, or run Setup.vbs.
  pause
  exit /b 1
)

if exist "python\python.exe" (
  "python\python.exe" serve.py --folder "%FOLDER%"
) else (
  python serve.py --folder "%FOLDER%"
)
pause
"""

README = """%(name)s -- the Firefox bundle
=================================

What this is
------------
The app, plus a small helper that hands it your synced folder. Firefox has no
File System Access API, so a web page there cannot reach a folder on its own;
this helper is the process that can. It binds 127.0.0.1 and nothing else can
reach it -- it is not a server, and no device ever syncs through it. Devices
share a folder, and that is all they share.

If you use Chrome or Edge you do not need any of this: open the hosted app and
let it pick the folder itself.

Installing
----------
1. Unzip this anywhere. There is no installer and nothing is written outside
   this folder.
2. Double-click  Setup.vbs
   It asks which folder your cloud client keeps in sync, puts "%(name)s" on
   your desktop, and starts the app in your browser at
   http://localhost:%(port)s/

That is the whole installation. From then on it is the desktop icon, which
opens no window of its own -- no console, ever.

Changing the folder
-------------------
Edit folder.txt, or delete it and run Setup.vbs again.

If nothing happens
------------------
Run %(name)s.bat. It is the same helper with a console window, so whatever went
wrong is printed there instead of being swallowed.

What is in here
---------------
  web/                the app itself
  serve.py            the helper -- Python 3 standard library only
  python/             an official embeddable Python, if this zip was built
                      with one; otherwise yours from PATH is used
  Setup.vbs           the installer: folder, shortcut, first launch
  %(name)s.bat        the same helper with a visible console, for diagnosing
  folder.txt          appears after setup: the folder you chose

Notes
-----
- No .exe is shipped on purpose, so Windows SmartScreen has nothing to warn
  about: the shortcut points at Microsoft's own signed pythonw.exe.
- Nothing here refers to anything outside this folder, so you can move it,
  copy it to another PC, or delete it in one go.
- The helper needs no admin rights, no pip and no network.
- Sync happens while the app is open. Close it and the folder is still yours;
  the next device to open it picks up whatever your cloud client delivered.
"""


def check_self_contained(texts: dict[str, str]) -> None:
    """Refuse to ship a file naming anything outside the unzipped folder.

    Cheap, and it catches the one mistake that cannot be caught here otherwise:
    a path from the build machine reaching a bundle that is meant to run on
    someone else's. Only the generated text files are scanned -- serve.py and
    the web build hold no host paths, and the runtime is Python's own zip.
    """
    forbidden = {
        "\\\\wsl": "a WSL share",
        "/mnt/": "a WSL mount of a Windows drive",
        str(ROOT): "this checkout",
    }
    for name, text in texts.items():
        lowered = text.lower()
        for needle, what in forbidden.items():
            if needle.lower() in lowered:
                raise SystemExit(
                    f"{name} names {what} ({needle!r}).\n"
                    f"  Everything in the bundle must resolve from the folder it was\n"
                    f"  unzipped into -- architecture.md 7.1."
                )


def crlf(text: str) -> str:
    """Windows line endings, whichever platform assembled the zip."""
    return text.replace("\r\n", "\n").replace("\n", "\r\n")


def png_size(data: bytes) -> tuple[int, int]:
    """Width and height out of a PNG's IHDR, which is always the first chunk."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    width, height = struct.unpack(">II", data[16:24])
    return width, height


def build_ico(pngs: list[bytes]) -> bytes:
    """An .ico wrapping PNGs as-is.

    Vista and later accept PNG-compressed entries, which is far less code than
    hand-rolling a BMP with its upside-down rows and separate AND mask -- and it
    means the shortcut's icon is the same artwork the PWA already ships rather
    than a second drawing to keep in step.
    """
    header = struct.pack("<HHH", 0, 1, len(pngs))
    offset = len(header) + 16 * len(pngs)
    entries, blob = b"", b""
    for data in pngs:
        width, height = png_size(data)
        entries += struct.pack(
            "<BBBBHHII",
            0 if width >= 256 else width,  # 0 means 256 in this format
            0 if height >= 256 else height,
            0,
            0,
            1,
            32,
            len(data),
            offset,
        )
        blob += data
        offset += len(data)
    return header + entries + blob


def fetch_embed_zip(version: str) -> Path:
    url = f"https://www.python.org/ftp/python/{version}/python-{version}-embed-amd64.zip"
    CACHE.mkdir(parents=True, exist_ok=True)
    dest = CACHE / f"python-{version}-embed-amd64.zip"
    if dest.exists() and dest.stat().st_size > 1_000_000:
        print(f"  cached {dest.name} ({dest.stat().st_size // 1024} KB)")
        return dest
    print(f"  downloading {url}")
    request = urllib.request.Request(url, headers={"User-Agent": "checklist-build"})
    try:
        with urllib.request.urlopen(request, timeout=180) as response:
            blob = response.read()
    except Exception as exc:  # noqa: BLE001 - the reason varies and all of them are fatal
        raise SystemExit(
            f"could not download the Python runtime: {exc}\n"
            f"  Fetch it by hand and save it as: {dest}\n"
            f"  Or build without it: make windows PYTHON_EMBED=skip"
        )
    dest.write_bytes(blob)
    print(f"  saved {dest.name} ({len(blob) // 1024} KB)")
    return dest


def add_tree(zf: zipfile.ZipFile, source: Path, prefix: str) -> int:
    count = 0
    for path in sorted(source.rglob("*")):
        if path.is_file():
            zf.write(path, f"{prefix}/{path.relative_to(source).as_posix()}")
            count += 1
    return count


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-python",
        action="store_true",
        help="omit the embeddable runtime; the launcher then uses Python from PATH",
    )
    parser.add_argument("--python-version", default=PYTHON_VERSION)
    args = parser.parse_args()

    if not DIST.is_dir():
        print("no dist/ to package. Run 'make build' first, or use 'make windows'.", file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    fields = {"name": APP_NAME, "port": PORT}

    runtime: Path | None = None
    if not args.no_python:
        print("python runtime:")
        runtime = fetch_embed_zip(args.python_version)

    icons = [
        (DIST / "icons" / name).read_bytes()
        for name in ("icon-192.png",)
        if (DIST / "icons" / name).is_file()
    ]

    texts = {
        "Setup.vbs": VBS % fields,
        f"{APP_NAME}.bat": BAT,
        "README.txt": README % fields,
    }
    check_self_contained(texts)

    print("assembling:")
    if OUT.exists():
        OUT.unlink()
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as zf:
        files = add_tree(zf, DIST, "web")
        print(f"  web/            {files} files")

        zf.write(PACKAGING / "serve.py", "serve.py")
        # CRLF on every text file: Notepad is what opens these, and cmd and
        # wscript are what read the other two.
        for name, text in texts.items():
            zf.writestr(name, crlf(text))
        print("  serve.py, Setup.vbs, launcher, README")

        if icons:
            zf.writestr(f"{APP_NAME}.ico", build_ico(icons))
            print("  icon")

        if runtime is not None:
            with zipfile.ZipFile(runtime) as embed:
                for name in embed.namelist():
                    if name.endswith("/"):
                        continue
                    zf.writestr(f"python/{name}", embed.read(name))
            print(f"  python/         from {runtime.name}")

    size = OUT.stat().st_size
    print(f"\n==> {OUT.relative_to(ROOT)}  ({size // 1024} KB)")
    if runtime is None:
        print("    built without a Python runtime; the launcher will use Python from PATH")
    print("    Unzip it on Windows and double-click Setup.vbs once.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
