#!/usr/bin/env python3
"""Assemble the Windows bundle: bundles/checklist-windows.zip.

    python3 scripts/build-windows.py                 with the Python runtime
    python3 scripts/build-windows.py --no-python     assets and helper only

`make windows` is the way in; this is what it runs, after `make build`.

architecture.md 7.1 settles what is in the zip and why it is a zip rather than
an installer: an official embeddable Python plus a shortcut to Microsoft's own
signed pythonw.exe. No .exe is produced, deliberately -- SmartScreen never
fires, and there is no installer, no pip and no admin rights anywhere in it.

The runtime is downloaded once into .build-cache/ and staged into the zip. That
download is the one thing here that touches the network, and --no-python skips
it for a machine that already has Python on PATH.

Python 3 stdlib only, so this runs anywhere the project does.
"""

from __future__ import annotations

import argparse
import struct
import sys
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"
PACKAGING = ROOT / "packaging" / "windows"
CACHE = ROOT / ".build-cache"
OUT = ROOT / "bundles" / "checklist-windows.zip"

PYTHON_VERSION = "3.12.10"
APP_NAME = "Checklist"
PORT = 38531

# A console window, so a failure is visible. The shortcut is the normal way in
# and uses pythonw.exe, which has none.
BAT = r"""@echo off
rem Generated by scripts/build-windows.py -- do not edit by hand.
rem The desktop shortcut is the normal way in; this one shows errors.
setlocal enabledelayedexpansion
cd /d "%~dp0"

if not exist "folder.txt" (
  echo.
  echo Which folder does your cloud client keep in sync?
  echo   for example  C:\Users\%USERNAME%\Dropbox\checklist
  echo.
  set /p FOLDER="Folder: "
  ^> folder.txt echo !FOLDER!
)
set /p FOLDER=<folder.txt

if exist "python\python.exe" (
  "python\python.exe" serve.py --folder "!FOLDER!"
) else (
  python serve.py --folder "!FOLDER!"
)
pause
"""

PS1 = r"""$ErrorActionPreference = 'Stop'
# Generated by scripts/build-windows.py. Run it once after unzipping; it puts
# %(name)s on the desktop and in this folder.
$here = $PSScriptRoot

$pythonw = Join-Path $here 'python\pythonw.exe'
if (-not (Test-Path $pythonw)) { $pythonw = 'pythonw.exe' }

$folderFile = Join-Path $here 'folder.txt'
if (-not (Test-Path $folderFile)) {
    $answer = Read-Host 'Which folder does your cloud client keep in sync?'
    Set-Content -Path $folderFile -Value $answer
}
$folder = (Get-Content $folderFile | Select-Object -First 1).Trim()
if (-not $folder) { throw 'no folder given; delete folder.txt and try again' }

$server    = Join-Path $here 'serve.py'
$arguments = '"{0}" --folder "{1}"' -f $server, $folder
$icon      = Join-Path $here '%(name)s.ico'

$shell = New-Object -ComObject WScript.Shell
foreach ($dir in @([Environment]::GetFolderPath('Desktop'), $here)) {
    $lnk = Join-Path $dir '%(name)s.lnk'
    $s = $shell.CreateShortcut($lnk)
    $s.TargetPath       = $pythonw
    $s.Arguments        = $arguments
    $s.IconLocation     = $icon
    $s.WorkingDirectory = $here
    $s.Description      = '%(name)s - opens in your browser'
    $s.Save()
    Write-Output "  shortcut: $lnk"
}
"""

README = """%(name)s -- the Firefox bundle
=================================

What this is
------------
The app, plus a small helper that hands it your synced folder. Firefox has no
File System Access API, so a web page there cannot reach a folder on its own;
this helper is the process that can. It binds 127.0.0.1 and nothing else can
reach it -- it is not a server, and no device ever syncs through it. Devices
share a folder, and that is all they share.

If you use Chrome or Edge you do not need any of this: open the hosted app and
let it pick the folder itself.

Installing
----------
1. Unzip this anywhere. There is no installer and nothing is written outside
   this folder.
2. Double-click  make-shortcut.ps1  ->  Run with PowerShell.
   It asks once which folder your cloud client keeps in sync, and puts
   "%(name)s" on your desktop.
3. Open %(name)s. It starts the helper and opens your browser at
   http://localhost:%(port)s/

If PowerShell refuses to run the script, use %(name)s.bat instead -- same thing,
with a console window so you can see what happened.

Changing the folder
-------------------
Edit folder.txt, or delete it and run make-shortcut.ps1 again.

What is in here
---------------
  web/                the app itself
  serve.py            the helper -- Python 3 standard library only
  python/             an official embeddable Python, if this zip was built
                      with one; otherwise use your own
  %(name)s.bat        launcher with a visible console
  make-shortcut.ps1   puts it on the desktop

Notes
-----
- No .exe is shipped on purpose, so Windows SmartScreen has nothing to warn
  about: the shortcut points at Microsoft's own signed pythonw.exe.
- The helper needs no admin rights, no pip and no network.
- Sync happens while the app is open. Close it and the folder is still yours;
  the next device to open it picks up whatever your cloud client delivered.
"""


def png_size(data: bytes) -> tuple[int, int]:
    """Width and height out of a PNG's IHDR, which is always the first chunk."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    width, height = struct.unpack(">II", data[16:24])
    return width, height


def build_ico(pngs: list[bytes]) -> bytes:
    """An .ico wrapping PNGs as-is.

    Vista and later accept PNG-compressed entries, which is far less code than
    hand-rolling a BMP with its upside-down rows and separate AND mask -- and it
    means the shortcut's icon is the same artwork the PWA already ships rather
    than a second drawing to keep in step.
    """
    header = struct.pack("<HHH", 0, 1, len(pngs))
    offset = len(header) + 16 * len(pngs)
    entries, blob = b"", b""
    for data in pngs:
        width, height = png_size(data)
        entries += struct.pack(
            "<BBBBHHII",
            0 if width >= 256 else width,  # 0 means 256 in this format
            0 if height >= 256 else height,
            0,
            0,
            1,
            32,
            len(data),
            offset,
        )
        blob += data
        offset += len(data)
    return header + entries + blob


def fetch_embed_zip(version: str) -> Path:
    url = f"https://www.python.org/ftp/python/{version}/python-{version}-embed-amd64.zip"
    CACHE.mkdir(parents=True, exist_ok=True)
    dest = CACHE / f"python-{version}-embed-amd64.zip"
    if dest.exists() and dest.stat().st_size > 1_000_000:
        print(f"  cached {dest.name} ({dest.stat().st_size // 1024} KB)")
        return dest
    print(f"  downloading {url}")
    request = urllib.request.Request(url, headers={"User-Agent": "checklist-build"})
    try:
        with urllib.request.urlopen(request, timeout=180) as response:
            blob = response.read()
    except Exception as exc:  # noqa: BLE001 - the reason varies and all of them are fatal
        raise SystemExit(
            f"could not download the Python runtime: {exc}\n"
            f"  Fetch it by hand and save it as: {dest}\n"
            f"  Or build without it: make windows PYTHON_EMBED=skip"
        )
    dest.write_bytes(blob)
    print(f"  saved {dest.name} ({len(blob) // 1024} KB)")
    return dest


def add_tree(zf: zipfile.ZipFile, source: Path, prefix: str) -> int:
    count = 0
    for path in sorted(source.rglob("*")):
        if path.is_file():
            zf.write(path, f"{prefix}/{path.relative_to(source).as_posix()}")
            count += 1
    return count


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-python",
        action="store_true",
        help="omit the embeddable runtime; the launcher then uses Python from PATH",
    )
    parser.add_argument("--python-version", default=PYTHON_VERSION)
    args = parser.parse_args()

    if not DIST.is_dir():
        print("no dist/ to package. Run 'make build' first, or use 'make windows'.", file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    fields = {"name": APP_NAME, "port": PORT}

    runtime: Path | None = None
    if not args.no_python:
        print("python runtime:")
        runtime = fetch_embed_zip(args.python_version)

    icons = [
        (DIST / "icons" / name).read_bytes()
        for name in ("icon-192.png",)
        if (DIST / "icons" / name).is_file()
    ]

    print("assembling:")
    if OUT.exists():
        OUT.unlink()
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as zf:
        files = add_tree(zf, DIST, "web")
        print(f"  web/            {files} files")

        zf.write(PACKAGING / "serve.py", "serve.py")
        zf.writestr(f"{APP_NAME}.bat", BAT)
        zf.writestr("make-shortcut.ps1", PS1 % fields)
        zf.writestr("README.txt", README % fields)
        print("  serve.py, launcher, shortcut, README")

        if icons:
            zf.writestr(f"{APP_NAME}.ico", build_ico(icons))
            print("  icon")

        if runtime is not None:
            with zipfile.ZipFile(runtime) as embed:
                for name in embed.namelist():
                    if name.endswith("/"):
                        continue
                    zf.writestr(f"python/{name}", embed.read(name))
            print(f"  python/         from {runtime.name}")

    size = OUT.stat().st_size
    print(f"\n==> {OUT.relative_to(ROOT)}  ({size // 1024} KB)")
    if runtime is None:
        print("    built without a Python runtime; the launcher will use Python from PATH")
    print("    Unzip it on Windows and run make-shortcut.ps1 once.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
